# Generated by Django 3.2.19 on 2023-05-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='AmoudIngredient',
        ),
    ]
