# Generated by Django 3.2.19 on 2023-05-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipeingredient_amoudingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmoudIngredient',
            new_name='AmountIngredient',
        ),
        migrations.RenameField(
            model_name='amountingredient',
            old_name='amound',
            new_name='amount',
        ),
    ]
