# Generated by Django 3.2.19 on 2023-05-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230522_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'ordering': ('ingredient__name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterUniqueTogether(
            name='amountingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
